config:
  target: 'http://localhost:3000' # API 서버 주소
  phases:
    - duration: 30 # 테스트 지속 시간 (초)
      arrivalRate: 1000 # 초당 요청 수

scenarios:
  - flow:
      - post:
          url: '/users' # 데이터를 삽입하는 엔드포인트
          json:
            name: 'user'
