config:
  target: 'http://localhost:3000' # API 서버 주소
  phases:
    - duration: 30 # 테스트 지속 시간 (초)
      arrivalRate: 1000 # 초당 요청 수
scenarios:
  - flow:
      - get:
          url: '/users' # 사용자 조회 엔드포인트

