// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDASlfoGMW07J3wGQmiq7lTWDrdqYFY4CY',
    appId: '1:1019174591714:web:1c98bb765bb0b8f8c3d2bb',
    messagingSenderId: '1019174591714',
    projectId: 'gavri-3a344',
    authDomain: 'gavri-3a344.firebaseapp.com',
    storageBucket: 'gavri-3a344.appspot.com',
    measurementId: 'G-25M4RBMTB9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZpyuDoUBm41XDmsmenPIZg4pMaUlGV64',
    appId: '1:1019174591714:android:2ad51fc58803aeaac3d2bb',
    messagingSenderId: '1019174591714',
    projectId: 'gavri-3a344',
    storageBucket: 'gavri-3a344.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj869hH-Fx1JMFRwwYGCBzBYnuciTU1J0',
    appId: '1:1019174591714:ios:b9a4e7fac3d535b9c3d2bb',
    messagingSenderId: '1019174591714',
    projectId: 'gavri-3a344',
    storageBucket: 'gavri-3a344.appspot.com',
    iosClientId: '1019174591714-42c3q2anhne8t539m5pl47k0lc82aol6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj869hH-Fx1JMFRwwYGCBzBYnuciTU1J0',
    appId: '1:1019174591714:ios:b9a4e7fac3d535b9c3d2bb',
    messagingSenderId: '1019174591714',
    projectId: 'gavri-3a344',
    storageBucket: 'gavri-3a344.appspot.com',
    iosClientId: '1019174591714-42c3q2anhne8t539m5pl47k0lc82aol6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatting',
  );
}
